"""
Django settings for boilerplate project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from core.functions import get_env_variable

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_variable("DJANGO_SECRET_KEY", "django-insecure-reemplazame!")

# django apps
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
]

# 3rd party apps
INSTALLED_APPS += [
    "django_json_widget",
    "template_partials",
    "django_extensions",
    "hijack",  # permite a los superusuarios "tomar" la sesión de otro usuario
    "hijack.contrib.admin",  # integración de hijack con el admin de django
    "django_htmx",  # integración de htmx con django
    "crispy_forms",
    "crispy_bootstrap5",  # integración de crispy forms con bootstrap 5
    "tinymce",  # editor WYSIWYG
    "rest_framework",
    "rest_framework.authtoken",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "corsheaders",  # CORS
]

# local apps
INSTALLED_APPS += [
    "polls.apps.PollsConfig",
    "cbvpolls.apps.CbvpollsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "hijack.middleware.HijackUserMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "builtins": ["template_partials.templatetags.partials"],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": get_env_variable("DJANGO_DB_ENGINE", "django.db.backends.sqlite3"),
        "NAME": get_env_variable("DJANGO_DB_NAME", BASE_DIR / "db.sqlite3"),
        "USER": get_env_variable("DJANGO_DB_USER", ""),
        "PASSWORD": get_env_variable("DJANGO_DB_PASSWORD", ""),
        "HOST": get_env_variable("DJANGO_DB_HOST", ""),
        "PORT": get_env_variable("DJANGO_DB_PORT", ""),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = "es-cl"
TIME_ZONE = "America/Santiago"
USE_I18N = True
USE_L10N = False
USE_TZ = True

DATETIME_FORMAT = "d/m/Y H:i"
DATETIME_FORMAT_ALAS = "d/m/Y \\a \\l\\a\\s H:i"
DATE_FORMAT = "d/m/Y"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = "/static/"
STATICFILES_DIRS = ("staticfiles",)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMAIL_BACKEND = get_env_variable("DJANGO_EMAIL_BACKEND", "django.core.mail.backends.console.EmailBackend")
EMAIL_HOST = get_env_variable("DJANGO_EMAIL_HOST", "")
EMAIL_PORT = get_env_variable("DJANGO_EMAIL_PORT", 587)
EMAIL_USE_TLS = get_env_variable("DJANGO_EMAIL_USE_TLS", True)
EMAIL_HOST_USER = get_env_variable("DJANGO_EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = get_env_variable("DJANGO_EMAIL_HOST_PASSWORD", "")

SERVER_EMAIL = get_env_variable("DJANGO_SERVER_EMAIL", "tds@dcc.uchile.cl")

SESSION_COOKIE_PATH = get_env_variable("DJANGO_COOKIE_PATH", "/")
CSRF_COOKIE_PATH = get_env_variable("DJANGO_COOKIE_PATH", "/")
LANGUAGE_COOKIE_PATH = get_env_variable("DJANGO_COOKIE_PATH", "/")

ADMINS = [
    ("Juan Arriagada", "jarriagada@dcc.uchile.cl"),
]

BASE_URL = get_env_variable("DJANGO_BASE_URL")

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "EXCEPTION_HANDLER": "rest_framework.views.exception_handler",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,  # Define cuántos elementos quieres mostrar por página
}

SPECTACULAR_SETTINGS = {
    "TITLE": "DCC APIs",
    "DESCRIPTION": "DCC boilerplate APIs",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
    "CONTACT": {
        "name": "tds@dcc.uchile.cl",
        "url": "dcc.uchile.cl",
        "email": "jarriagada@dcc.uchile.cl",
    },
    "SERVERS": [{"url": get_env_variable("DJANGO_SPECTACULAR_SERVER")}],
}

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"http:\/\/localhost(.)*",
]

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}
