name: Code Checks

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8

    - name: Run Black
      run: |
        black --check ./src --config ./src/pyproject.toml

    - name: Run Flake8
      run: |
        flake8 ./src --config ./src/.flake8
